### ISSUE TITLE
[Feature]: Anyscale cluster module

### ISSUE THREAD

**Issue by elebiodaslingshot** [anyscale/terraform-aws-anyscale-cloudfoundation-modules#11]
### What are you looking for?

Module for provisioning an anyscale cluster.

### Which module(s)?

- [X] Root Anyscale Module
- [ ] aws-anyscale-efs
- [ ] aws-anyscale-iam
- [ ] aws-anyscale-s3
- [ ] aws-anyscale-s3-policy
- [ ] aws-anyscale-securitygroups
- [ ] aws-anyscale-vpc

### Is it blocking work?

no

### Terraform version

None

**Comment by brent-anyscale** [comment]
These modules are for building the underlying AWS architecture. @elebiodaslingshot - are you asking to be able to build resources within Anyscale via Terraform?

**Comment by elebiodaslingshot** [comment]
`resources within Anyscale via Terraform` this exactly. Not sure how possible/clean it would be, assuming you have to do local execs 🤮 but was curious if planning on it.

**Comment by brent-anyscale** [comment]
We do have a request from other customers for creating an Anyscale Terraform Provider. Since our API is public, this should be relatively straight forward - however, our APIs are going through a refactoring and we're waiting for those to settle. That said, I've loosely started this project, but there is no timeline currently attached to it. I'll tag Slingshot as another customer that is interested in this functionality.
